### ISSUE TITLE
Tried 100 things but can't let it work... (VPNUNLIMITED CUSTOM .OVPN)

### ISSUE THREAD

**Issue by poudenes** [haugene/vpn-configs-contrib#103]
### Do you have the latest provider files?

- [X] I have checked that the provider are the latest

### Have you tested the provider files?

- [X] I have tested the provider files

### Can you create a PR for this config?

- [ ] I can create a PR for this

### Provider details

Hi All,

I tried to let this work. I have created a custom .OVPN file at VPNunlimited portal. This OVPN file have a server specific for torrents. I mount the file as written in documents. But its unclear what to do with:

```
      OPENVPN_PROVIDER: custom
      OPENVPN_CONFIG: nl
```
Here is my compose:
```
version: '3.3'
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission
    hostname: transmission
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/data/torrents:/data:rw
      - /volume1/docker/transmission/ovpn/default.ovpn:/etc/openvpn/custom/default.ovpn

    environment:
      TZ: Europe/Amsterdam
      PUID: 1026
      PGID: 100
      OPENVPN_PROVIDER: custom
      OPENVPN_CONFIG: nl
      OPENVPN_USERNAME: username
      OPENVPN_PASSWORD: password
    ports:
       - 9091:9091
  
```
