### ISSUE TITLE
Cannot resolve host address 

### ISSUE THREAD

**Issue by Moohan** [haugene/vpn-configs-contrib#121]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to the container/transmission?

- [X] I have checked the container repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

```
transmission-openvpn:
    cap_add:
      - NET_ADMIN
    container_name: transmission-openvpn
    environment:
      - OPENVPN_PROVIDER=PROTONVPN
      - OPENVPN_CONFIG=nl.protonvpn.com.udp,ch.protonvpn.com.udp,se.protonvpn.com.udp,es.protonvpn.com.udp
      - OPENVPN_USERNAME=**None**
      - OPENVPN_PASSWORD=**None**
      - LOCAL_NETWORK=192.168.86.0/24
      - 'TZ=${TZ}'
      - TRANSMISSION_ALT_SPEED_UP=10
      - TRANSMISSION_ALT_SPEED_DOWN=200
      - TRANSMISSION_ALT_SPEED_TIME_ENABLED=true
      - TRANSMISSION_ALT_SPEED_TIME_BEGIN=640
      - TRANSMISSION_ALT_SPEED_TIME_END=1410
      - TRANSMISSION_PEER_SOCKET_TOS='lowcost'
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=3
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
      - TRANSMISSIOB_IDLE_SEEDING_LIMIT=720
    image: haugene/transmission-openvpn
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '6767:6767'
      - '7878:7878'
      - '8787:8787'
      - '8989:8989'
      - '9696:9696'
      - '9091:9091'
    restart: unless-stopped
    volumes:
      - '${ROOT}/downloads:/data'
      - './proton-vpn_credentials.txt:/config/openvpn-credentials.txt'
```

### Current Behavior

Container does not start / gets stuck in boot loop. It randomises through all the addresses but get the same issue with all of them.

### Expected Behavior

I've used this setup for a while and it's always (mostly) been fine.

The proton VPN configs were changed recently and I switched to them, they were working fine, but it stopped working in the last day or two.

### How have you tried to solve the problem?

?

### Log output

```
Creating transmission-openvpn ... done
Attaching to transmission-openvpn
transmission-openvpn    | Starting container with revision: 44c82aa1297b0f4473ad141f2cea326b407d9c22
transmission-openvpn    | Creating TUN device /dev/net/tun
transmission-openvpn    | Using OpenVPN provider: PROTONVPN
transmission-openvpn    | Running with VPN_CONFIG_SOURCE auto
transmission-openvpn    | No bundled config script found for PROTONVPN. Defaulting to external config
transmission-openvpn    | Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.0NGXympSvo
transmission-openvpn    | Extracting configs to /tmp/tmp.8kRWeBWmqc
transmission-openvpn    | Found configs for PROTONVPN in /tmp/tmp.8kRWeBWmqc/vpn-configs-contrib-main/openvpn/protonvpn, will replace current content in /etc/openvpn/protonvpn
transmission-openvpn    | Cleanup: deleting /tmp/tmp.0NGXympSvo and /tmp/tmp.8kRWeBWmqc
transmission-openvpn    | 4 servers found in OPENVPN_CONFIG, se.protonvpn.com.udp chosen randomly
transmission-openvpn    | Starting OpenVPN using config se.protonvpn.com.udp.ovpn
transmission-openvpn    | Modifying /etc/openvpn/protonvpn/se.protonvpn.com.udp.ovpn for best behaviour in this container
transmission-openvpn    | Modification: Point auth-user-pass option to the username/password file
transmission-openvpn    | Modification: Change ca certificate path
transmission-openvpn    | Modification: Change ping options
transmission-openvpn    | Modification: Update/set resolv-retry to 15 seconds
transmission-openvpn    | Modification: Change tls-crypt keyfile path
transmission-openvpn    | Modification: Set output verbosity to 3
transmission-openvpn    | Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
transmission-openvpn    | Found existing OPENVPN credentials at /config/openvpn-credentials.txt
transmission-openvpn    | adding route to local network 192.168.86.0/24 via 172.18.0.1 dev eth0
transmission-openvpn    | Fri Jun 24 08:19:53 2022 OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar 22 2022
transmission-openvpn    | Fri Jun 24 08:19:53 2022 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
transmission-openvpn    | Fri Jun 24 08:19:53 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission-openvpn    | Fri Jun 24 08:19:53 2022 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
transmission-openvpn    | Fri Jun 24 08:19:53 2022 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
transmission-openvpn    | Fri Jun 24 08:19:54 2022 RESOLVE: Cannot resolve host address: se.protonvpn.com:4569 (No address associated with hostname)
transmission-openvpn    | Fri Jun 24 08:19:54 2022 RESOLVE: Cannot resolve host address: se.protonvpn.com:4569 (No address associated with hostname)
transmission-openvpn    | Fri Jun 24 08:19:59 2022 RESOLVE: Cannot resolve host address: se.protonvpn.com:4569 (No address associated with hostname)
transmission-openvpn    | Fri Jun 24 08:20:04 2022 RESOLVE: Cannot resolve host address: se.protonvpn.com:4569 (No address associated with hostname)
transmission-openvpn    | Fri Jun 24 08:20:04 2022 Could not determine IPv4/IPv6 protocol
transmission-openvpn    | Fri Jun 24 08:20:04 2022 SIGTERM[soft,init_instance] received, process exiting

^C
Gracefully stopping... (press Ctrl+C again to force)
Stopping transmission-openvpn ... done
```

### Environment

```markdown
- OS:Raspbian GNU/Linux 10 (buster)
- Docker: 20.10.17
```
