### ISSUE TITLE
NordVPN url changes

### ISSUE THREAD

**Issue by PleaseStopAsking** [haugene/vpn-configs-contrib#14]
## Before creating this request I have:

**REQUIRED**
- [X] Searched for similar [provider requests][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the provider, custom provider, troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the request as possible
- [X] Agreed that my request will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Which provider?

**REQUIRED**
```txt
NordVPN
```

### Where are the configs?

**REQUIRED**
```txt
https://nordvpn.com/ovpn/
```
### Additional context

I noticed yesterday that my container was in a constant reboot loop and after digging into the logs, found that it was failing to grab a config file from ```https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/***.udp.ovpn```. Attempting to hit that endpoint outside the container also failed with 502's (which is still the case as of now).

I tried to locate any updates from the Nord side but could see no posting or status messages but after review of their site, it seems they have changed the url where users should download the configs from.

*Old Url Example*
```https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/***.udp.ovpn```

*New Url Example*
```
https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/al18.nordvpn.com.udp1194.ovpn
https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/al18.nordvpn.com.tcp443.ovpn
```

**Comment by PleaseStopAsking** [comment]
Issue seems to be hit or miss as I have just let the container continue to restart on its own over the last few days and about once a day, it starts to work and actually makes a connection.

Just a few notes from my additional digging.

- If I walk through the updateConfigs.sh script line by line manually directly on my host, it seems to work and returns valid responses.

- The logs show the following each time the problem arises.
```
Starting container with revision: acf1261567b01b3e31bf4f7e8bc119284aaa0240
transmission     | Creating TUN device /dev/net/tun
transmission     | Using OpenVPN provider: NORDVPN
transmission     | Provider NORDVPN has a custom setup script, executing it
transmission     | 2021-05-18 18:36:35 Checking curl installation
transmission     | 2021-05-18 18:36:35 Removing existing configs
transmission     | 2021-05-18 18:36:35 Selecting the best server...
transmission     | 2021-05-18 18:36:35 Searching for technology: openvpn_udp
transmission     | 2021-05-18 18:36:35 Unable to find a server with the specified parameters, using any recommended server
transmission     | 2021-05-18 18:36:35 Best server : 
transmission     | 2021-05-18 18:36:35 Downloading config: default.ovpn
transmission     | 2021-05-18 18:36:35 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/.udp.ovpn
transmission     | 2021-05-18 18:36:35 Selecting the best server...
transmission     | 2021-05-18 18:36:35 Searching for technology: openvpn_udp
transmission     | 2021-05-18 18:36:35 Unable to find a server with the specified parameters, using any recommended server
transmission     | 2021-05-18 18:36:35 Best server : 
transmission     | 2021-05-18 18:36:35 Downloading config: .ovpn
transmission     | 2021-05-18 18:36:35 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/.udp.ovpn
transmission     | No VPN configuration provided. Using default.
transmission     | Modifying /etc/openvpn/nordvpn/default.ovpn for best behaviour in this container
transmission     | Setting OpenVPN credentials...
transmission     | adding route to local network 192.168.4.0/24 via 172.18.0.1 dev eth0
transmission     | Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/default.ovpn:1: html (2.5.0)
transmission     | Use --help for more information.
```

- Compose for reference
```
  transmission:
    image: haugene/transmission-openvpn:3.6
    container_name: transmission
    hostname: transmission
    restart: unless-stopped
    #dns:
    #  - 1.1.1.1
    #  - 1.0.0.1
    ports:
      - "9091:9091"
    volumes:
      - ./docker-configs/transmission/config:/config
      - ${data_folder_path}:/data
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=${transmission_openvpn_username}
      - OPENVPN_PASSWORD=${transmission_openvpn_password}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - NORDVPN_CATEGORY=legacy_p2p
      - NORDVPN_COUNTRY=US
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=${docker_host_network_cidr}
      - TZ=${timezone}
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - TRANSMISSION_RATIO_LIMIT=1
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_WATCH_DIR_ENABLED=false
      - TRANSMISSION_LPD_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=30
      - TRANSMISSION_HOME=${transmission_home_dir}
      - TRANSMISSION_DOWNLOAD_DIR=${transmission_downloaded_dir}
      - TRANSMISSION_INCOMPLETE_DIR=${transmission_incomplete_dir}
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
```

- The curl test in the documentation always fails but if I switch to another site for grabbing my ip, it seemingly works fine. I also tested curl on an ubuntu based image and it also works fine. I am not sure what to make of this result as I would expect it to work regardless of the base image used or endpoint being hit.
```
docker run --rm -it alpine sh -c "apk add curl && curl ipecho.net/plain"     fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/5) Installing ca-certificates (20191127-r5)
(2/5) Installing brotli-libs (1.0.9-r3)
(3/5) Installing nghttp2-libs (1.42.0-r1)
(4/5) Installing libcurl (7.76.1-r0)
(5/5) Installing curl (7.76.1-r0)
Executing busybox-1.32.1-r6.trigger
Executing ca-certificates-20191127-r5.trigger
OK: 8 MiB in 19 packages
curl: (6) Could not resolve host: ipecho.net


docker run --rm -it alpine sh -c "apk add curl && curl https://api.ipify.org?format=json"
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/5) Installing ca-certificates (20191127-r5)
(2/5) Installing brotli-libs (1.0.9-r3)
(3/5) Installing nghttp2-libs (1.42.0-r1)
(4/5) Installing libcurl (7.76.1-r0)
(5/5) Installing curl (7.76.1-r0)
Executing busybox-1.32.1-r6.trigger
Executing ca-certificates-20191127-r5.trigger
OK: 8 MiB in 19 packages
{"ip":"<redacted>"}
```
