### ISSUE TITLE
ProtonVPN migration from node-us-XXX

### ISSUE THREAD

**Issue by retrodaredevil** [haugene/vpn-configs-contrib#159]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to the container/transmission?

- [X] I have checked the container repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

```
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - './transmission-data:/data'
        environment:
            - OPENVPN_PROVIDER=PROTONVPN
            #- OPENVPN_CONFIG=node-us-129.protonvpn.com.udp
            - OPENVPN_CONFIG=us.protonvpn.net.udp
            - OPENVPN_USERNAME=***
            - OPENVPN_PASSWORD=***
            - LOCAL_NETWORK=192.168.0.0/16
            - TZ=America/Chicago
        logging:
            driver: json-file
            options:
                max-size: 10m
#        ports:
#            - '9091:9091'
        image: haugene/transmission-openvpn
        restart: unless-stopped
```

### Current Behavior

I was using proton VPN for a while, then it stopped working with transmission. I believe this is not a transmission-openvpn issue because I see that there were breaking changes for ProtonVPN recently.

### Expected Behavior

I would like some info on how to migrate from `node-us-129.protonvpn.com.udp`. I took a peek at #157 but it doesn't look like anyone had any migration tips.

### How have you tried to solve the problem?

I tried `node-us-129.protonvpn.com.udp`, but obviously that isn't a valid server. I notice that the log output tells me what servers I can use, but I have no idea how these servers relate to what I was previously using.

### Log output

```
transmission-openvpn-transmission-openvpn-1  | Supplied config us.protonvpn.net.udp.ovpn could not be found.
transmission-openvpn-transmission-openvpn-1  | Your options for this provider are:
transmission-openvpn-transmission-openvpn-1  | ch.protonvpn.net.tcp.ovpn
transmission-openvpn-transmission-openvpn-1  | ch.protonvpn.net.udp.ovpn
transmission-openvpn-transmission-openvpn-1  | cz.protonvpn.net.tcp.ovpn
transmission-openvpn-transmission-openvpn-1  | cz.protonvpn.net.udp.ovpn
transmission-openvpn-transmission-openvpn-1  | es.protonvpn.net.tcp.ovpn
transmission-openvpn-transmission-openvpn-1  | es.protonvpn.net.udp.ovpn
transmission-openvpn-transmission-openvpn-1  | hk.protonvpn.net.tcp.ovpn
transmission-openvpn-transmission-openvpn-1  | hk.protonvpn.net.udp.ovpn
transmission-openvpn-transmission-openvpn-1  | hu.protonvpn.net.tcp.ovpn
transmission-openvpn-transmission-openvpn-1  | hu.protonvpn.net.udp.ovpn
transmission-openvpn-transmission-openvpn-1  | is.protonvpn.net.tcp.ovpn
transmission-openvpn-transmission-openvpn-1  | is.protonvpn.net.udp.ovpn
transmission-openvpn-transmission-openvpn-1  | ng.protonvpn.net.tcp.ovpn
transmission-openvpn-transmission-openvpn-1  | ng.protonvpn.net.udp.ovpn
transmission-openvpn-transmission-openvpn-1  | nl.protonvpn.net.tcp.ovpn
transmission-openvpn-transmission-openvpn-1  | nl.protonvpn.net.udp.ovpn
transmission-openvpn-transmission-openvpn-1  | pl.protonvpn.net.tcp.ovpn
transmission-openvpn-transmission-openvpn-1  | pl.protonvpn.net.udp.ovpn
transmission-openvpn-transmission-openvpn-1  | ro.protonvpn.net.tcp.ovpn
transmission-openvpn-transmission-openvpn-1  | ro.protonvpn.net.udp.ovpn
transmission-openvpn-transmission-openvpn-1  | se.protonvpn.net.tcp.ovpn
transmission-openvpn-transmission-openvpn-1  | se.protonvpn.net.udp.ovpn
transmission-openvpn-transmission-openvpn-1  | sg.protonvpn.net.tcp.ovpn
transmission-openvpn-transmission-openvpn-1  | sg.protonvpn.net.udp.ovpn
transmission-openvpn-transmission-openvpn-1  | NB: Remember to not specify .ovpn as part of the config name.
```

### Environment

```markdown
sudo docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```


### Anything else?

I'm really just asking for support here as I'm a little annoyed that an update in this repository caused a problem in my docker container that I had left running for a while, but upon restart (and probably an update) it started acting up. I want to use a ProtonVPN server in Chicago and I'm really not sure which one to choose now.
