### ISSUE TITLE
Auth failure for ProtonVPN

### ISSUE THREAD

**Issue by rastacalavera** [haugene/vpn-configs-contrib#232]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to the container/transmission?

- [X] I have checked the container repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

```
    transmission:
        image: haugene/transmission-openvpn
        container_name: transmission
        volumes:
            - ./config/transmission:/config
            - /home/**REMOVED**/**REMOVED**/config/ovpn/:/etc/openvpn/custom/
        environment:
            - PUID=1000
            - PGID=1000
            - CREATE_TUN_DEVICE=true
#protonVPN
            - OPENVPN_PROVIDER=custom
            - OPENVPN_CONFIG=node-ca-09.protonvpn.net.udp
            - OPENVPN_USERNAME=**REMOVED**
            - OPENVPN_PASSWORD=**REMOVED**
            - WEBPROXY_ENABLED=false
            - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false
            - TRANSMISSION_SEED_QUEUE_ENABLED=false
            - LOCAL_NETWORK=10.10.0.0/24,10.10.1.0/24,100.64.0.0/10,10.0.0.0/24
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
        restart: unless-stopped

```

### Current Behavior

Cannot authorize with proton vpn service. 

### Expected Behavior

Expect the connection to work.

### How have you tried to solve the problem?

Tried with and without user/pasword file

### Log output

`2023-08-16T15:19:11.337203693Z 2023-08-16 15:19:11 OpenVPN 2.5.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 14 2022
2023-08-16T15:19:11.337213874Z 2023-08-16 15:19:11 library versions: OpenSSL 3.0.2 15 Mar 2022, LZO 2.10
2023-08-16T15:19:11.337422095Z 2023-08-16 15:19:11 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2023-08-16T15:19:11.338725019Z 2023-08-16 15:19:11 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
2023-08-16T15:19:11.338736581Z 2023-08-16 15:19:11 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
2023-08-16T15:19:11.338889113Z 2023-08-16 15:19:11 TCP/UDP: Preserving recently used remote address: [AF_INET]178.249.214.65:80
2023-08-16T15:19:11.338914257Z 2023-08-16 15:19:11 Socket Buffers: R=[212992->212992] S=[212992->212992]
2023-08-16T15:19:11.338924830Z 2023-08-16 15:19:11 UDP link local: (not bound)
2023-08-16T15:19:11.338939748Z 2023-08-16 15:19:11 UDP link remote: [AF_INET]178.249.214.65:80
2023-08-16T15:19:11.381762236Z 2023-08-16 15:19:11 TLS: Initial packet from [AF_INET]178.249.214.65:80, sid=d79dabf9 899ffcf8
2023-08-16T15:19:11.532828698Z 2023-08-16 15:19:11 VERIFY OK: depth=2, C=CH, O=ProtonVPN AG, CN=ProtonVPN Root CA
2023-08-16T15:19:11.533942047Z 2023-08-16 15:19:11 VERIFY OK: depth=1, C=CH, O=ProtonVPN AG, CN=ProtonVPN Intermediate CA 1
2023-08-16T15:19:11.535044120Z 2023-08-16 15:19:11 VERIFY KU OK
2023-08-16T15:19:11.535095533Z 2023-08-16 15:19:11 Validating certificate extended key usage
2023-08-16T15:19:11.535117689Z 2023-08-16 15:19:11 ++ Certificate has EKU (str) TLS Web Client Authentication, expects TLS Web Server Authentication
2023-08-16T15:19:11.535405193Z 2023-08-16 15:19:11 ++ Certificate has EKU (oid) 1.3.6.1.5.5.7.3.2, expects TLS Web Server Authentication
2023-08-16T15:19:11.535439026Z 2023-08-16 15:19:11 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2023-08-16T15:19:11.535457764Z 2023-08-16 15:19:11 VERIFY EKU OK
2023-08-16T15:19:11.535474357Z 2023-08-16 15:19:11 VERIFY OK: depth=0, CN=node-ca-09.protonvpn.net
2023-08-16T15:19:11.582893926Z 2023-08-16 15:19:11 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1633', remote='link-mtu 1634'
2023-08-16T15:19:11.582971626Z 2023-08-16 15:19:11 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
2023-08-16T15:19:11.583222329Z 2023-08-16 15:19:11 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 4096 bit RSA, signature: RSA-SHA256
2023-08-16T15:19:11.583301417Z 2023-08-16 15:19:11 [node-ca-09.protonvpn.net] Peer Connection Initiated with [AF_INET]178.249.214.65:80
2023-08-16T15:19:12.632646265Z 2023-08-16 15:19:12 SENT CONTROL [node-ca-09.protonvpn.net]: 'PUSH_REQUEST' (status=1)
2023-08-16T15:19:17.728665424Z 2023-08-16 15:19:17 SENT CONTROL [node-ca-09.protonvpn.net]: 'PUSH_REQUEST' (status=1)
2023-08-16T15:19:17.769237284Z 2023-08-16 15:19:17 AUTH: Received control message: AUTH_FAILED
2023-08-16T15:19:17.769889524Z 2023-08-16 15:19:17 SIGTERM[soft,auth-failure] received, process exiting
`

### Environment

```markdown
- OS:Ubuntu 22.04.4
- Docker:24.0.5, build ced0996
```
