### ISSUE TITLE
Container crashing when trying to retrieve VPN configs

### ISSUE THREAD

**Issue by Qhilm** [haugene/vpn-configs-contrib#241]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to the container/transmission?

- [X] I have checked the container repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

```yaml
version: '3.8'
services:
  transmission-openvpn:
    container_name: 'haugene'
    cap_add:
      - NET_ADMIN
    devices:
      - '/dev/net/tun'
    volumes:
      - /volume1/data/transmission-data/:/data
      - /volume1/data/haugene/resolv.conf:/etc/resolv.conf
      - /volume1/data/haugene/:/config
    environment:
      - OPENVPN_PROVIDER=PROTONVPN
      - OPENVPN_CONFIG=dk.protonvpn.net.udp
      - OPENVPN_USERNAME=**None**
      - OPENVPN_PASSWORD=**None**
      - LOCAL_NETWORK=192.168.1.0/24
      - OVERRIDE_DNS_1=94.140.14.14
      - OVERRIDE_DNS_2=149.112.112.112
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      #- TRANSMISSION_RATIO_LIMIT=3
      #- TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=1000
    logging:
      driver: json-file
      options:
        max-size: 10m
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - '9091:9091'
    image: haugene/transmission-openvpn:dev

networks:
  default:
    external:
      name: mybridge
```

### Current Behavior

Container crashes at start with this error:

>error: Your local changes to the following files would be overwritten by merge:
>	openvpn/privado/updateConfigs.sh
>Please commit your changes or stash them before you merge.

The issue started somewhere in the last 8 days, it was working fine 8 days ago and as far as I can tell ourobouros did not upgrade this container in the last 8 days.

### Expected Behavior

container starting normally

### How have you tried to solve the problem?

1. tried the dev channel
2. DNS seems to work because I can see this in the logs:
>Will get configs from https://github.com/haugene/vpn-configs-contrib.git
>Repository is already cloned, checking for update

### Log output

Starting container with revision: 52d432ddca774080040627e3b6ec61fc9e6b0ac7
TRANSMISSION_HOME is currently set to: /config/transmission-home
One or more OVERRIDE_DNS addresses found. Will use them to overwrite /etc/resolv.conf
Creating TUN device /dev/net/tun
Using OpenVPN provider: PROTONVPN
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for PROTONVPN. Defaulting to external config
Will get configs from https://github.com/haugene/vpn-configs-contrib.git
Repository is already cloned, checking for update
error: Your local changes to the following files would be overwritten by merge:
	openvpn/privado/updateConfigs.sh
Please commit your changes or stash them before you merge.
Aborting
Updating 45cc9b305..35ec20293

### Environment

```markdown
- OS: DSM 7.2
- Docker: 20.10.23
```
